//go:build linux

package ebpf

// The BPF object and its Go bindings are generated by bpf2go and committed, so
// `go build` needs no clang/llvm. Regenerate (when trace.bpf.c changes) with the
// pinned toolchain via the multi-stage build: `make bpf-generate`.
//
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target bpfel -no-strip trace ./bpf/trace.bpf.c
