//go:build ignore

// mksysname generates per-arch syscall number→name tables from
// golang.org/x/sys/unix's zsysnum_linux_<arch>.go files (the authoritative,
// already-vendored source). Run via `go generate ./internal/ebpf/`.
//
// Per-arch output is required because syscall numbers differ across
// architectures (e.g. openat is 257 on amd64, 56 on arm64).
package main

import (
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var arches = []string{"amd64", "arm64"}

// Lines like:  SYS_OPENAT = 56
var sysRe = regexp.MustCompile(`^\s*SYS_([A-Z0-9_]+)\s*=\s*(\d+)`)

func main() {
	modDir, err := moduleDir("golang.org/x/sys")
	if err != nil {
		fail(err)
	}
	for _, arch := range arches {
		src := fmt.Sprintf("%s/unix/zsysnum_linux_%s.go", modDir, arch)
		names, err := parse(src)
		if err != nil {
			fail(fmt.Errorf("%s: %w", arch, err))
		}
		if err := emit(arch, names); err != nil {
			fail(err)
		}
		fmt.Printf("sysname_linux_%s.go: %d syscalls\n", arch, len(names))
	}
}

func moduleDir(mod string) (string, error) {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", mod).Output()
	if err != nil {
		return "", fmt.Errorf("locate module %s: %w", mod, err)
	}
	return strings.TrimSpace(string(out)), nil
}

func parse(path string) (map[int]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	names := map[int]string{}
	for _, line := range strings.Split(string(data), "\n") {
		m := sysRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		nr, err := strconv.Atoi(m[2])
		if err != nil {
			continue
		}
		// libseccomp/OCI use the lowercase kernel syscall name.
		if _, exists := names[nr]; !exists {
			names[nr] = strings.ToLower(m[1])
		}
	}
	return names, nil
}

func emit(arch string, names map[int]string) error {
	nrs := make([]int, 0, len(names))
	for nr := range names {
		nrs = append(nrs, nr)
	}
	sort.Ints(nrs)

	var b strings.Builder
	b.WriteString("// Code generated by mksysname.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "//go:build linux && %s\n\n", arch)
	b.WriteString("package ebpf\n\n")
	b.WriteString("// nrToName maps syscall numbers to names for this architecture,\n")
	b.WriteString("// generated from golang.org/x/sys/unix.\n")
	b.WriteString("var nrToName = map[int]string{\n")
	for _, nr := range nrs {
		fmt.Fprintf(&b, "\t%d: %q,\n", nr, names[nr])
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format %s: %w", arch, err)
	}
	return os.WriteFile(fmt.Sprintf("sysname_linux_%s.go", arch), formatted, 0o644)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "mksysname:", err)
	os.Exit(1)
}
