// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceConnKey struct {
	_      structs.HostLayout
	Tgid   uint32
	Family uint32
	Dport  uint16
	Pad    uint16
	Daddr  [16]uint8
}

type traceConnStat struct {
	_     structs.HostLayout
	Count uint64
	Proto uint32
	Pad   uint32
}

type tracePathBuf struct {
	_    structs.HostLayout
	Path [256]int8
}

type traceWriteStat struct {
	_         structs.HostLayout
	Count     uint64
	Bytes     uint64
	SampleLen uint32
	Sample    [256]uint8
	_         [4]byte
}

// loadTrace returns the embedded CollectionSpec for trace.
func loadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace: %w", err)
	}

	return spec, err
}

// loadTraceObjects loads trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceObjects
//	*tracePrograms
//	*traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceSpecs struct {
	traceProgramSpecs
	traceMapSpecs
	traceVariableSpecs
}

// traceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceProgramSpecs struct {
	HandleCap      *ebpf.ProgramSpec `ebpf:"handle_cap"`
	HandleConnect  *ebpf.ProgramSpec `ebpf:"handle_connect"`
	HandleDnsSend  *ebpf.ProgramSpec `ebpf:"handle_dns_send"`
	HandleExec     *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleFork     *ebpf.ProgramSpec `ebpf:"handle_fork"`
	HandleOpen     *ebpf.ProgramSpec `ebpf:"handle_open"`
	HandleRename   *ebpf.ProgramSpec `ebpf:"handle_rename"`
	HandleSysEnter *ebpf.ProgramSpec `ebpf:"handle_sys_enter"`
	HandleUnlink   *ebpf.ProgramSpec `ebpf:"handle_unlink"`
	HandleUnshare  *ebpf.ProgramSpec `ebpf:"handle_unshare"`
	HandleWrite    *ebpf.ProgramSpec `ebpf:"handle_write"`
}

// traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceMapSpecs struct {
	ConnStats  *ebpf.MapSpec `ebpf:"conn_stats"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	Launcher   *ebpf.MapSpec `ebpf:"launcher"`
	Seen       *ebpf.MapSpec `ebpf:"seen"`
	SeenCaps   *ebpf.MapSpec `ebpf:"seen_caps"`
	Tracked    *ebpf.MapSpec `ebpf:"tracked"`
	WritePaths *ebpf.MapSpec `ebpf:"write_paths"`
	WriteStats *ebpf.MapSpec `ebpf:"write_stats"`
}

// traceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceVariableSpecs struct {
}

// traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceObjects struct {
	tracePrograms
	traceMaps
	traceVariables
}

func (o *traceObjects) Close() error {
	return _TraceClose(
		&o.tracePrograms,
		&o.traceMaps,
	)
}

// traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceMaps struct {
	ConnStats  *ebpf.Map `ebpf:"conn_stats"`
	Events     *ebpf.Map `ebpf:"events"`
	Launcher   *ebpf.Map `ebpf:"launcher"`
	Seen       *ebpf.Map `ebpf:"seen"`
	SeenCaps   *ebpf.Map `ebpf:"seen_caps"`
	Tracked    *ebpf.Map `ebpf:"tracked"`
	WritePaths *ebpf.Map `ebpf:"write_paths"`
	WriteStats *ebpf.Map `ebpf:"write_stats"`
}

func (m *traceMaps) Close() error {
	return _TraceClose(
		m.ConnStats,
		m.Events,
		m.Launcher,
		m.Seen,
		m.SeenCaps,
		m.Tracked,
		m.WritePaths,
		m.WriteStats,
	)
}

// traceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceVariables struct {
}

// tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracePrograms struct {
	HandleCap      *ebpf.Program `ebpf:"handle_cap"`
	HandleConnect  *ebpf.Program `ebpf:"handle_connect"`
	HandleDnsSend  *ebpf.Program `ebpf:"handle_dns_send"`
	HandleExec     *ebpf.Program `ebpf:"handle_exec"`
	HandleFork     *ebpf.Program `ebpf:"handle_fork"`
	HandleOpen     *ebpf.Program `ebpf:"handle_open"`
	HandleRename   *ebpf.Program `ebpf:"handle_rename"`
	HandleSysEnter *ebpf.Program `ebpf:"handle_sys_enter"`
	HandleUnlink   *ebpf.Program `ebpf:"handle_unlink"`
	HandleUnshare  *ebpf.Program `ebpf:"handle_unshare"`
	HandleWrite    *ebpf.Program `ebpf:"handle_write"`
}

func (p *tracePrograms) Close() error {
	return _TraceClose(
		p.HandleCap,
		p.HandleConnect,
		p.HandleDnsSend,
		p.HandleExec,
		p.HandleFork,
		p.HandleOpen,
		p.HandleRename,
		p.HandleSysEnter,
		p.HandleUnlink,
		p.HandleUnshare,
		p.HandleWrite,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_bpfel.o
var _TraceBytes []byte
