// Package profile turns an observed behavior graph (one Run) into sandbox
// profiles: a firejail profile and an OCI-style seccomp profile.
//
// Honesty about strength (this matters — an over-claimed profile breaks programs
// or gives false confidence):
//
//   - The firejail FILESYSTEM + EXEC whitelist is genuinely evidence-based: it
//     lists exactly the files the program opened and the binaries it exec'd.
//     This is jailgraph's real value-add over a generic profile.
//   - The seccomp syscall policy is NOT a least-privilege allowlist. The
//     collector observes only a curated set of rare, security-relevant syscalls
//     (never the hot path), so we cannot know the full syscall set. Instead we
//     take a permissive baseline and DENY the dangerous syscalls the program
//     demonstrably never used ("baseline minus unobserved-dangerous"). A tight
//     allowlist needs the eBPF backend's full coverage (a later increment).
//   - Capability/namespace policy is NOT emitted from observation: increment 1
//     does not yet decode capset/setns into Capability/Namespace nodes. firejail
//     output uses a conservative `caps.drop all` DEFAULT, clearly labeled as a
//     default rather than evidence.
package profile

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// GateableSyscalls is the set of dangerous, security-relevant syscalls the
// collector watches. The seccomp policy denies whichever of these the run never
// invoked. Kept in sync with internal/seccomp's flagged set, but defined here as
// portable strings so this package builds on every platform.
var GateableSyscalls = []string{
	"execve", "execveat",
	"clone", "clone3", "fork", "vfork",
	"open", "openat", "openat2",
	"unshare", "setns",
	"capset",
}

// Behavior is the observed surface of one run, reduced to what the profiles
// need. Caps/Namespaces are intentionally absent (not yet decoded).
type Behavior struct {
	RunID    string
	Target   string
	Syscalls map[string]bool // observed syscall names
	Files    []string        // observed opened paths
	Binaries []string        // observed exec'd binary paths
	Lossy    bool            // the trace dropped events; profile is unsafe
}

// DeniedSyscalls returns the gateable syscalls the run never invoked — the ones
// the seccomp policy denies. Sorted for deterministic output.
func (b Behavior) DeniedSyscalls() []string {
	var denied []string
	for _, sc := range GateableSyscalls {
		if !b.Syscalls[sc] {
			denied = append(denied, sc)
		}
	}
	sort.Strings(denied)
	return denied
}

// ociSeccomp is the subset of the OCI runtime-spec seccomp schema we emit.
type ociSeccomp struct {
	DefaultAction string            `json:"defaultAction"`
	Architectures []string          `json:"architectures,omitempty"`
	Syscalls      []ociSyscallRule  `json:"syscalls"`
	Comment       map[string]string `json:"_comment,omitempty"`
}

type ociSyscallRule struct {
	Names  []string `json:"names"`
	Action string   `json:"action"`
}

// RenderSeccompOCI emits an OCI seccomp profile. It is default-ALLOW with an
// explicit ERRNO deny list — an honest encoding of "permissive baseline minus
// the dangerous syscalls this run never used". It is deliberately NOT
// default-deny, because the collector lacks full syscall coverage.
func RenderSeccompOCI(b Behavior) ([]byte, error) {
	denied := b.DeniedSyscalls()
	prof := ociSeccomp{
		DefaultAction: "SCMP_ACT_ALLOW",
		Syscalls:      []ociSyscallRule{},
		Comment: map[string]string{
			"generated_by": "jailgraph",
			"run":          b.RunID,
			"strength":     "baseline-allow minus dangerous-syscall gating; NOT a least-privilege allowlist (collector lacks hot-path coverage)",
		},
	}
	if len(denied) > 0 {
		prof.Syscalls = append(prof.Syscalls, ociSyscallRule{Names: denied, Action: "SCMP_ACT_ERRNO"})
	}
	return json.MarshalIndent(prof, "", "  ")
}

// RenderFirejail emits a firejail .profile. Its filesystem/exec whitelist is
// evidence-based; the seccomp.drop line mirrors the OCI deny list; caps and net
// are conservative defaults, labeled as such.
func RenderFirejail(b Behavior) string {
	var sb strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&sb, format, a...); sb.WriteByte('\n') }

	w("# firejail profile generated by jailgraph for run %s (target: %s)", b.RunID, b.Target)
	if b.Lossy {
		w("# WARNING: trace was lossy — this profile is incomplete and may break the program.")
	}
	w("")

	w("# --- evidence-based filesystem whitelist (observed opens) ---")
	dirs := observedDirs(b.Files)
	if len(dirs) == 0 {
		w("# (no file opens observed)")
	}
	for _, d := range dirs {
		w("whitelist %s", d)
	}
	w("")

	w("# --- dangerous syscalls the program never used (denied) ---")
	denied := b.DeniedSyscalls()
	if len(denied) > 0 {
		w("seccomp.drop %s", strings.Join(denied, ","))
	} else {
		w("# (program used all watched syscalls; none denied)")
	}
	w("")

	w("# --- conservative DEFAULTS (not from observation) ---")
	w("# no capability evidence is collected yet; drop all by default.")
	w("caps.drop all")
	w("# no network syscalls are observed yet; assume none. Remove if the program needs net.")
	w("net none")
	w("nonewprivs")
	w("noroot")
	return sb.String()
}

// observedDirs reduces opened file paths to their parent directories, sorted and
// de-duplicated, for a compact firejail whitelist.
func observedDirs(files []string) []string {
	seen := map[string]struct{}{}
	for _, f := range files {
		if f == "" {
			continue
		}
		d := filepath.Dir(f)
		seen[d] = struct{}{}
	}
	out := make([]string, 0, len(seen))
	for d := range seen {
		out = append(out, d)
	}
	sort.Strings(out)
	return out
}
